from typing import Optional, TYPE_CHECKING
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.tools import Tool as LangchainTool
import uuid

from app.Tools.base_tool import BaseTool
from app.Tools.tool_input_parser import ToolInputParser
from app.LLM.memory import Memory
from app.Types.agent_types import SupervisorToolInput

if TYPE_CHECKING:
    from app.Agents.supervisor import SupervisorAgent

class SupervisorTool(BaseTool):
    def __init__(self, llm: BaseChatModel, task_id: str, memory: Optional[Memory] = None, supervisor_agent: Optional["SupervisorAgent"] = None):
        """
        Initializes the SupervisorTool with a language model and optional memory.

        Input:
        - llm: A chat-based LLM instance that powers the SupervisorAgent.
        - task_id: A unique identifier for a task
        - memory: Optional memory object to retain conversation history/context.

        The constructor sets up a `SupervisorAgent` internally to handle task planning and delegation.
        """
        super().__init__(
            name="supervisor",
            description="""Supervisor Agent assigns tasks to specialized sub-agents, ensuring each part of a complex workflow is handled by 
                    the most suitable agent.""",
            memory=memory,
            args_schema=SupervisorToolInput
        )
        self.supervisor_agent = supervisor_agent

    async def run(self, inputs: SupervisorToolInput) -> str:
        """
        Asynchronously executes the tool by delegating to the internal SupervisorAgent.

        Input:
        - inputs: A dictionary or string containing the task details.
        Expected fields (if a dict):
            - "query": the user’s question or task,
            - "system_info": any relevant system metadata,
            - "screenshot": optional base64 screenshot or image context.

        Returns:
        - A response string generated by the SupervisorAgent after task planning.

        Raises:
        - Any errors during parsing or invocation will propagate up unless handled by the caller.
        """

        query = inputs.query
        system_info = inputs.system_info

        tool_call_id = str(uuid.uuid4())
        response = await self.supervisor_agent.invoke(
            query=query,
            system_info=system_info,
            tool_call_id = tool_call_id
        )
        return response
        
