from typing import Optional
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.tools import Tool as LangchainTool

from app.Tools.base_tool import BaseTool
from app.Tools.tool_input_parser import ToolInputParser
from app.Agents.supervisor import SupervisorAgent
from app.LLM.memory import Memory

class SupervisorTool(BaseTool):
    def __init__(self, llm: BaseChatModel, memory: Optional[Memory] = None):
        """
        Initializes the SupervisorTool with a language model and optional memory.

        Input:
        - llm: A chat-based LLM instance that powers the SupervisorAgent.
        - memory: Optional memory object to retain conversation history/context.

        The constructor sets up a `SupervisorAgent` internally to handle task planning and delegation.
        """
        super().__init__(
            name="Supervisor",
            description="Plans and delegates tasks to sub-agents.",
            memory=memory
        )
        self.supervisor_agent = SupervisorAgent(llm=llm, memory=memory)

    async def run(self, inputs: dict | str) -> str:
        """
        Asynchronously executes the tool by delegating to the internal SupervisorAgent.

        Input:
        - inputs: A dictionary or string containing the task details.
        Expected fields (if a dict):
            - "query": the user’s question or task,
            - "system_info": any relevant system metadata,
            - "screenshot": optional base64 screenshot or image context.

        Returns:
        - A response string generated by the SupervisorAgent after task planning.

        Raises:
        - Any errors during parsing or invocation will propagate up unless handled by the caller.
        """

        parsed = ToolInputParser.parse(inputs)
        response = await self.supervisor_agent.invoke(
            query=parsed["query"],
            system_info=parsed["system_info"],
            screenshot=parsed["screenshot"]
        )
        return response
        
